alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - alertmanager.52.86.221.235.nip.io
grafana:
  enabled: false
kubeStateMetrics:
  enabled: false
prometheus:
  enabled: false
nodeExporter:
  enabled: false
