alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - alertmanager.k.root-servers.net..nip.io
grafana:
  enabled: false
kubeStateMetrics:
  enabled: false
prometheus:
  enabled: false
nodeExporter:
  enabled: false
