alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - alertmanager.54.209.84.108.nip.io
grafana:
  enabled: false
kubeStateMetrics:
  enabled: false
prometheus:
  enabled: false
nodeExporter:
  enabled: false
